import os; dest_dir = 'tests/example_ds2_tfrecords'
files = [os.path.join(dest_dir, x) for x in os.listdir(dest_dir)]
from tfrecords_creator import read_shards
#  imgs, labels, texts, bbox_labels, bbox_coords = read_shards(files, None, 3)
#  image, label, text, synset, bbox_coords, bbox_labels, objects = read_shards(files, None, 3)
examples = read_shards(files, None, 3)
import py3nvml; py3nvml.grab_gpus(0)
import tensorflow as tf; sess = tf.Session(); sess.run(tf.global_variables_initializer())
#  a,b,c,d,e = sess.run((imgs, labels, texts, bbox_labels, bbox_coords))
#  a,b,c,d,e,f,g = sess.run((image, label, text, synset, bbox_coords, bbox_labels, objects))
a,c,d,e,f,g = sess.run((examples.images, examples.texts, examples.synsets, examples.num_bboxes, examples.bbox_coords, examples.bbox_labels))
a,b,c,d,e,f,g = sess.run((examples.images, examples.labels, examples.texts, examples.synsets, examples.num_bboxes, examples.bbox_coords, examples.bbox_labels))
print(a.shape)
print(b)
print(c)
print(d)
print(e)
print(f[2])
print(g[2])
#  print(d)
#  print(e)
